name: ncm
channels:
- conda-forge
- defaults
dependencies:
- docopt
- feedparser>=6.0
- furo
- gdal
- geopandas>=0.10
- gitpython
- numba
- owslib
- pandas
- pcraster
- pip
- pip:
    - cbsodata
- pre-commit
- pylint
- python=3.9
- rasterio
- ruamel.yaml
- schema
- scipy
- sphinx
- tqdm
